// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.9.2
// source: api/rpc/command.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlayerCommandService_Dispatch_FullMethodName     = "/globalmail.rpc.PlayerCommandService/Dispatch"
	PlayerCommandService_ListCommands_FullMethodName = "/globalmail.rpc.PlayerCommandService/ListCommands"
)

// PlayerCommandServiceClient is the client API for PlayerCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerCommandServiceClient interface {
	Dispatch(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error)
}

type playerCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerCommandServiceClient(cc grpc.ClientConnInterface) PlayerCommandServiceClient {
	return &playerCommandServiceClient{cc}
}

func (c *playerCommandServiceClient) Dispatch(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, PlayerCommandService_Dispatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerCommandServiceClient) ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error) {
	out := new(ListCommandsResponse)
	err := c.cc.Invoke(ctx, PlayerCommandService_ListCommands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerCommandServiceServer is the server API for PlayerCommandService service.
// All implementations must embed UnimplementedPlayerCommandServiceServer
// for forward compatibility
type PlayerCommandServiceServer interface {
	Dispatch(context.Context, *CommandRequest) (*CommandResponse, error)
	ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error)
	mustEmbedUnimplementedPlayerCommandServiceServer()
}

// UnimplementedPlayerCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlayerCommandServiceServer struct {
}

func (UnimplementedPlayerCommandServiceServer) Dispatch(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedPlayerCommandServiceServer) ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommands not implemented")
}
func (UnimplementedPlayerCommandServiceServer) mustEmbedUnimplementedPlayerCommandServiceServer() {}

// UnsafePlayerCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerCommandServiceServer will
// result in compilation errors.
type UnsafePlayerCommandServiceServer interface {
	mustEmbedUnimplementedPlayerCommandServiceServer()
}

func RegisterPlayerCommandServiceServer(s grpc.ServiceRegistrar, srv PlayerCommandServiceServer) {
	s.RegisterService(&PlayerCommandService_ServiceDesc, srv)
}

func _PlayerCommandService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerCommandServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerCommandService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerCommandServiceServer).Dispatch(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerCommandService_ListCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerCommandServiceServer).ListCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerCommandService_ListCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerCommandServiceServer).ListCommands(ctx, req.(*ListCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerCommandService_ServiceDesc is the grpc.ServiceDesc for PlayerCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "globalmail.rpc.PlayerCommandService",
	HandlerType: (*PlayerCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _PlayerCommandService_Dispatch_Handler,
		},
		{
			MethodName: "ListCommands",
			Handler:    _PlayerCommandService_ListCommands_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rpc/command.proto",
}
