// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/rpc/command.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameCommandService_Dispatch_FullMethodName     = "/globalmail.rpc.GameCommandService/Dispatch"
	GameCommandService_ListCommands_FullMethodName = "/globalmail.rpc.GameCommandService/ListCommands"
)

// GameCommandServiceClient is the client API for GameCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameCommandServiceClient interface {
	Dispatch(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error)
}

type gameCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameCommandServiceClient(cc grpc.ClientConnInterface) GameCommandServiceClient {
	return &gameCommandServiceClient{cc}
}

func (c *gameCommandServiceClient) Dispatch(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, GameCommandService_Dispatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameCommandServiceClient) ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error) {
	out := new(ListCommandsResponse)
	err := c.cc.Invoke(ctx, GameCommandService_ListCommands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameCommandServiceServer is the server API for GameCommandService service.
// All implementations must embed UnimplementedGameCommandServiceServer
// for forward compatibility
type GameCommandServiceServer interface {
	Dispatch(context.Context, *CommandRequest) (*CommandResponse, error)
	ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error)
	mustEmbedUnimplementedGameCommandServiceServer()
}

// UnimplementedGameCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameCommandServiceServer struct {
}

func (UnimplementedGameCommandServiceServer) Dispatch(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedGameCommandServiceServer) ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommands not implemented")
}
func (UnimplementedGameCommandServiceServer) mustEmbedUnimplementedGameCommandServiceServer() {}

// UnsafeGameCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameCommandServiceServer will
// result in compilation errors.
type UnsafeGameCommandServiceServer interface {
	mustEmbedUnimplementedGameCommandServiceServer()
}

func RegisterGameCommandServiceServer(s grpc.ServiceRegistrar, srv GameCommandServiceServer) {
	s.RegisterService(&GameCommandService_ServiceDesc, srv)
}

func _GameCommandService_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCommandServiceServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameCommandService_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCommandServiceServer).Dispatch(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameCommandService_ListCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameCommandServiceServer).ListCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameCommandService_ListCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameCommandServiceServer).ListCommands(ctx, req.(*ListCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameCommandService_ServiceDesc is the grpc.ServiceDesc for GameCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "globalmail.rpc.GameCommandService",
	HandlerType: (*GameCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dispatch",
			Handler:    _GameCommandService_Dispatch_Handler,
		},
		{
			MethodName: "ListCommands",
			Handler:    _GameCommandService_ListCommands_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rpc/command.proto",
}
