syntax = "proto3";

package globalmail.rpc;

option go_package = "globalmail/api/rpc;rpc";

service GatewayService {
  rpc ResolveRoute(RouteRequest) returns (RouteResponse);
  rpc ClearRoute(RouteRequest) returns (ClearRouteResponse);
  rpc Heartbeat(HeartbeatRequest) returns (HeartbeatResponse);
}

message RouteRequest {
  int64 uid = 1;
}

message RouteResponse {
  string instance_id = 1;
  string grpc_addr = 2;
  string frpc_addr = 3;
  int32 weight = 4;
}

message ClearRouteResponse {
  bool ok = 1;
}

message HeartbeatRequest {
  int64 uid = 1;
  string conn_id = 2;
  int64 seq = 3;
  int64 client_timestamp = 4;
}

message HeartbeatResponse {
  bool ok = 1;
  int64 seq = 2;
  int64 server_timestamp = 3;
  string expire_at = 4;
}
