// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.9.2
// source: api/rpc/mail.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PlayerMailService_ListGlobalMails_FullMethodName    = "/globalmail.rpc.PlayerMailService/ListGlobalMails"
	PlayerMailService_MarkGlobalMailRead_FullMethodName = "/globalmail.rpc.PlayerMailService/MarkGlobalMailRead"
	PlayerMailService_ClaimGlobalMail_FullMethodName    = "/globalmail.rpc.PlayerMailService/ClaimGlobalMail"
	PlayerMailService_DeleteGlobalMail_FullMethodName   = "/globalmail.rpc.PlayerMailService/DeleteGlobalMail"
)

// PlayerMailServiceClient is the client API for PlayerMailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerMailServiceClient interface {
	ListGlobalMails(ctx context.Context, in *ListGlobalMailsRequest, opts ...grpc.CallOption) (*ListGlobalMailsResponse, error)
	MarkGlobalMailRead(ctx context.Context, in *GlobalMailStateRequest, opts ...grpc.CallOption) (*GlobalMailStateResponse, error)
	ClaimGlobalMail(ctx context.Context, in *ClaimGlobalMailRequest, opts ...grpc.CallOption) (*GlobalMailStateResponse, error)
	DeleteGlobalMail(ctx context.Context, in *GlobalMailStateRequest, opts ...grpc.CallOption) (*GlobalMailStateResponse, error)
}

type playerMailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerMailServiceClient(cc grpc.ClientConnInterface) PlayerMailServiceClient {
	return &playerMailServiceClient{cc}
}

func (c *playerMailServiceClient) ListGlobalMails(ctx context.Context, in *ListGlobalMailsRequest, opts ...grpc.CallOption) (*ListGlobalMailsResponse, error) {
	out := new(ListGlobalMailsResponse)
	err := c.cc.Invoke(ctx, PlayerMailService_ListGlobalMails_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerMailServiceClient) MarkGlobalMailRead(ctx context.Context, in *GlobalMailStateRequest, opts ...grpc.CallOption) (*GlobalMailStateResponse, error) {
	out := new(GlobalMailStateResponse)
	err := c.cc.Invoke(ctx, PlayerMailService_MarkGlobalMailRead_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerMailServiceClient) ClaimGlobalMail(ctx context.Context, in *ClaimGlobalMailRequest, opts ...grpc.CallOption) (*GlobalMailStateResponse, error) {
	out := new(GlobalMailStateResponse)
	err := c.cc.Invoke(ctx, PlayerMailService_ClaimGlobalMail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerMailServiceClient) DeleteGlobalMail(ctx context.Context, in *GlobalMailStateRequest, opts ...grpc.CallOption) (*GlobalMailStateResponse, error) {
	out := new(GlobalMailStateResponse)
	err := c.cc.Invoke(ctx, PlayerMailService_DeleteGlobalMail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayerMailServiceServer is the server API for PlayerMailService service.
// All implementations must embed UnimplementedPlayerMailServiceServer
// for forward compatibility
type PlayerMailServiceServer interface {
	ListGlobalMails(context.Context, *ListGlobalMailsRequest) (*ListGlobalMailsResponse, error)
	MarkGlobalMailRead(context.Context, *GlobalMailStateRequest) (*GlobalMailStateResponse, error)
	ClaimGlobalMail(context.Context, *ClaimGlobalMailRequest) (*GlobalMailStateResponse, error)
	DeleteGlobalMail(context.Context, *GlobalMailStateRequest) (*GlobalMailStateResponse, error)
	mustEmbedUnimplementedPlayerMailServiceServer()
}

// UnimplementedPlayerMailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlayerMailServiceServer struct {
}

func (UnimplementedPlayerMailServiceServer) ListGlobalMails(context.Context, *ListGlobalMailsRequest) (*ListGlobalMailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGlobalMails not implemented")
}
func (UnimplementedPlayerMailServiceServer) MarkGlobalMailRead(context.Context, *GlobalMailStateRequest) (*GlobalMailStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkGlobalMailRead not implemented")
}
func (UnimplementedPlayerMailServiceServer) ClaimGlobalMail(context.Context, *ClaimGlobalMailRequest) (*GlobalMailStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimGlobalMail not implemented")
}
func (UnimplementedPlayerMailServiceServer) DeleteGlobalMail(context.Context, *GlobalMailStateRequest) (*GlobalMailStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGlobalMail not implemented")
}
func (UnimplementedPlayerMailServiceServer) mustEmbedUnimplementedPlayerMailServiceServer() {}

// UnsafePlayerMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerMailServiceServer will
// result in compilation errors.
type UnsafePlayerMailServiceServer interface {
	mustEmbedUnimplementedPlayerMailServiceServer()
}

func RegisterPlayerMailServiceServer(s grpc.ServiceRegistrar, srv PlayerMailServiceServer) {
	s.RegisterService(&PlayerMailService_ServiceDesc, srv)
}

func _PlayerMailService_ListGlobalMails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGlobalMailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerMailServiceServer).ListGlobalMails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerMailService_ListGlobalMails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerMailServiceServer).ListGlobalMails(ctx, req.(*ListGlobalMailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerMailService_MarkGlobalMailRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalMailStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerMailServiceServer).MarkGlobalMailRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerMailService_MarkGlobalMailRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerMailServiceServer).MarkGlobalMailRead(ctx, req.(*GlobalMailStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerMailService_ClaimGlobalMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimGlobalMailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerMailServiceServer).ClaimGlobalMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerMailService_ClaimGlobalMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerMailServiceServer).ClaimGlobalMail(ctx, req.(*ClaimGlobalMailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerMailService_DeleteGlobalMail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalMailStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerMailServiceServer).DeleteGlobalMail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerMailService_DeleteGlobalMail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerMailServiceServer).DeleteGlobalMail(ctx, req.(*GlobalMailStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayerMailService_ServiceDesc is the grpc.ServiceDesc for PlayerMailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerMailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "globalmail.rpc.PlayerMailService",
	HandlerType: (*PlayerMailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGlobalMails",
			Handler:    _PlayerMailService_ListGlobalMails_Handler,
		},
		{
			MethodName: "MarkGlobalMailRead",
			Handler:    _PlayerMailService_MarkGlobalMailRead_Handler,
		},
		{
			MethodName: "ClaimGlobalMail",
			Handler:    _PlayerMailService_ClaimGlobalMail_Handler,
		},
		{
			MethodName: "DeleteGlobalMail",
			Handler:    _PlayerMailService_DeleteGlobalMail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rpc/mail.proto",
}
